version: '3.3'

services:
  db:
    image: mysql:8.2.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: Dras3U37rqJlNe
      MYSQL_ROOT_PASSWORD: der432DGQDYe4fgdRd
    volumes:
       - ./data:/var/lib/mysql

  cache:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=123

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    links:
      - php
      - node
    volumes:
      - ./cfg:/etc/nginx/conf.d
  php:
    build:
      context: ./php
    working_dir: /var/www/html    
    restart: always
    ports:
      - "9000:9000"
    links:
      - db
      - cache
    volumes:
      - ./back/public:/var/www/html

  node:
    image: node:bookworm
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./front/build:/home/node/app
    command: "node app.js"
 
volumes:
  redis:
  redis-config:

